const meaningless = new Set([".", "ok", "lol", "😂", "🔥", "👍", "first"]);
const linkPattern = /(https?:\/\/|www\.|bit\.ly|t\.me|discord\.gg)/i;
const spamPattern = /\b(dm me|check my profile|click my profile|visit my page|free money|giveaway|promo|promote|cheap prices|followers|collab|sub4sub|telegram only)\b/i;
const sexualPattern = /\b(sex|nude|onlyfans|xxx|horny)\b/i;
const hatePattern = /\b(kill yourself|idiot|stupid|hate you|trash|moron)\b/i;
const politicalPattern = /\b(election|president|left wing|right wing|politics)\b/i;
const reviewPattern = /\b(copied|buying views|botted|bot|bots|deleting negative|ai generated|chatgpt|generated by|generated by the same|automated|auto replies|auto responder|engagement bait|paid subscribers|copy pasted|crypto bots|suspiciously high engagement|replies sound corporate|zero soul|black mirror|dystopian)\b|(?:look|looks|feel|feels|sound|sounds)\s.{0,24}\bfake\b|\bfake\s(?:comments|views|reactions|positivity)\b/i;
const emojiOnlyPattern = /^[\p{Emoji_Presentation}\p{Extended_Pictographic}\s]+$/u;

export function analyzeComment(comment) {
  const normalized = comment.trim().toLowerCase();
  const language = detectLanguage(comment);

  if (meaningless.has(normalized) || normalized.length <= 2 || emojiOnlyPattern.test(normalized)) {
    return deletion("meaningless", language);
  }

  if (linkPattern.test(comment)) return deletion("link", language);
  if (spamPattern.test(comment)) return deletion("spam", language);
  if (sexualPattern.test(comment)) return deletion("sexual", language);
  if (hatePattern.test(comment)) return deletion("hate", language);
  if (politicalPattern.test(comment)) return deletion("political", language);
  if (looksDuplicated(normalized)) return deletion("duplicate", language);
  if (!hasPositiveComparisonContext(comment) && !/\b(less fake|not fake)\b/i.test(comment) && reviewPattern.test(comment)) {
    return review("sensitive_or_negative", language);
  }
  if (language.code === "unknown" || language.confidence < 0.45) return deletion("unclear_language", language);
  if (!isPositiveAsmrComment(normalized) && normalized.split(/\s+/).length <= 2 && normalized.length < 12) {
    return deletion("unclear", language);
  }

  return {
    action: "reply",
    category: "safe",
    detectedLanguage: language.name,
    replyLanguage: language.name,
    languageConfidence: language.confidence,
    reply: generateWarmReply(comment, language.code),
  };
}

export function validateReply(reply, maxLength = 120) {
  if (!reply || reply === "DELETE") return { safe: false, reason: "empty_or_delete" };
  if (reply.length > maxLength) return { safe: false, reason: "too_long" };
  if (linkPattern.test(reply)) return { safe: false, reason: "contains_link" };
  if (spamPattern.test(reply)) return { safe: false, reason: "promotional" };
  if (sexualPattern.test(reply)) return { safe: false, reason: "nsfw" };
  return { safe: true };
}

function deletion(category, language) {
  return {
    action: "delete",
    category,
    detectedLanguage: language.name,
    replyLanguage: null,
    languageConfidence: language.confidence,
    reply: "DELETE",
  };
}

function review(category, language) {
  return {
    action: "review",
    category,
    detectedLanguage: language.name,
    replyLanguage: null,
    languageConfidence: language.confidence,
    reply: "REVIEW",
  };
}

function looksDuplicated(text) {
  const words = text.split(/\s+/).filter(Boolean);
  return words.length >= 4 && new Set(words).size <= Math.ceil(words.length / 2);
}

function isPositiveAsmrComment(text) {
  return /\b(nice|relax|relaxing|calming|tingles|amazing|perfect|love|sleepy|so good|good sounds|soft sounds|w video|bro cooked|fell asleep|lowkey fire|fire tho|slapped tho|kinda relaxing|got me|i should sleep)\b/i.test(text);
}

function hasPositiveComparisonContext(text) {
  return /\b(compared to|instead of|rather than|unlike|way better than|more natural than|less annoying than|those channels|modern content|most videos|most channels)\b/i.test(text)
    || /\b(don't|don’t|doesn't|doesn’t|isn't|isn’t|aren't|aren’t|not)\b.{0,100}\bfake reactions\b/i.test(text);
}

function detectLanguage(comment) {
  const text = comment.toLowerCase();
  const latinWords = comment.match(/[a-z]{2,}/gi) || [];
  if (/[а-яё]/i.test(comment)) return { code: "ru", name: "Russian", confidence: 0.97 };
  if (/\b(love from|love this|love it)\b/i.test(text)) {
    return { code: "en", name: "English", confidence: 0.92 };
  }
  if (/[áéíóúñ¿¡]/i.test(comment) || /\b(gracias|hola|perfecta|relajante|sonido|dormir|microfono|aqui)\b/i.test(text)) {
    return { code: "es", name: "Spanish", confidence: 0.93 };
  }
  if (/[àâçéèêëîïôûùüÿœ]/i.test(comment) || /\b(merci|bonjour|relaxant|sommeil|parfait)\b/i.test(text)) {
    return { code: "fr", name: "French", confidence: 0.9 };
  }
  if (/[äöüß]/i.test(comment) || /\b(danke|entspannend|schlaf|perfekt|gerausch)\b/i.test(text)) {
    return { code: "de", name: "German", confidence: 0.9 };
  }
  if (/\b(thank|thanks|sleep|relax|relaxing|calming|sound|sounds|mic|nice|perfect|helped|watching|tingles|love this|amazing|w video|bro cooked|lowkey fire|slapped tho)\b/i.test(text)) {
    return { code: "en", name: "English", confidence: 0.92 };
  }
  if (latinWords.length >= 2) {
    return { code: "en", name: "English", confidence: 0.62 };
  }
  return { code: "unknown", name: "Unknown", confidence: 0.2 };
}

function generateWarmReply(comment, languageCode) {
  const text = comment.toLowerCase();
  const replyBank = {
    en: {
      sleep: "So glad it helped you relax. Sleep well tonight.",
      sound: "Thank you, I'm glad the sounds felt good.",
      fallback: "Thank you for watching, I'm really glad you enjoyed it.",
    },
    es: {
      sleep: "Me alegra mucho que te haya ayudado a relajarte.",
      sound: "Gracias, me alegra que los sonidos se sientan bien.",
      fallback: "Gracias por mirar, me alegra mucho que te haya gustado.",
    },
    ru: {
      sleep: "Рада, что видео помогло расслабиться. Спокойной ночи.",
      sound: "Спасибо, рада, что звук тебе понравился.",
      fallback: "Спасибо за просмотр, очень рада, что тебе понравилось.",
    },
    fr: {
      sleep: "Ravi que la video t'ait aide a te detendre.",
      sound: "Merci, content que les sons soient agreables.",
      fallback: "Merci d'avoir regarde, je suis content que ca t'ait plu.",
    },
    de: {
      sleep: "Freut mich, dass es dir beim Entspannen geholfen hat.",
      sound: "Danke, schon dass sich die Sounds gut anfuhlen.",
      fallback: "Danke fürs Zuschauen, freut mich sehr, dass es dir gefallt.",
    },
  };

  const replies = replyBank[languageCode] || replyBank.en;
  if (text.includes("sleep") || text.includes("relax") || text.includes("calming")) {
    return replies.sleep;
  }
  if (text.includes("sound") || text.includes("sounds") || text.includes("mic") || text.includes("sonido") || text.includes("microfono")) {
    return replies.sound;
  }
  return replies.fallback;
}
