const meaningless = new Set([".", "ok", "lol", "😂", "first"]);
const linkPattern = /(https?:\/\/|\bwww\.|bit\.ly|t\.me|discord\.gg)/i;
const spamPattern = /\b(dm me|check my profile|click my profile|visit my page|free money|giveaway|promo|promote|cheap prices|followers|collab|sub4sub|telegram only)\b/i;
const channelMentionPattern = /(^|\s)@[a-z0-9_.-]{3,}/i;
const sexualPattern = /\b(sex|nude|nudes|onlyfans|xxx|horny|boobs?|booty|bootie|ass|pimp|p\.i\.m\.p|fetish|kiss me|be with you|tetas?|sisas?|sisama|payaso|leite nas suas)\b/i;
const explicitSexualPattern = /\b(anal|anus|butt\s*plug|dildo|vibrator|porn|porno|pornhub|naked|undress|blowjob|handjob|suck\s+(?:my\s+)?(?:dick|cock)|dick|cock|penis|vagina|pussy|clit|cum|orgasm|masturbat(?:e|ing|ion)|nudes?|boobs?|tits?|horny|fetish|feet\s*(?:pics?|video)|sexo|sexual|desnud[ao]s?|culo|coño|polla|pene|vagina|buceta|bunda|pau|pica|xana|nua|nu[ao]|sexe|nu(?:e|s)?|bite|chatte|cul|seks|porno|ciplak|sik|amcik)\b/i;
const turkishSexualPattern = /(çıplak|göt|amcık)/i;
const cyrillicSexualPattern = /(анальн[а-я]*|анус|задниц[а-я]*|жоп[а-я]*|секс|порно|интим|гол[а-я]*|сиськ[а-я]*|груд[ьяи]|возбуд[а-я]*|трах[а-я]*|член|хуй|пизд[а-я]*|еб[а-я]*)/i;
const softAppearancePattern = /\b(sexy|gorgeous|pretty|cute|sweet|belle|beau|bonita|linda|guapa|hermosa|красив[а-я]+|мила[яа]|красот[а-я]+)\b/i;
const sexualContextPattern = /\b(lit|bed)\b.{0,48}\b(défaire|defaire|undress|unmake)\b|\b(défaire|defaire|undress|unmake)\b.{0,48}\b(lit|bed)\b|\b(show|send|more|want|need)\b.{0,24}\b(feet|foot)\b|\b(feet|foot)\b.{0,24}\b(pics?|video|please|pls)\b/i;
const greekSexualPattern = /(μουν[αά]ρ[αά]|βυζι[αά]|κωλ[οό]ς|σεξ)/i;
const hatePattern = /\b(kill yourself|idiot|stupid|hate you|trash|moron)\b/i;
const politicalPattern = /\b(election|president|left wing|right wing|politics)\b/i;
const reviewPattern = /\b(copied|buying views|botted|bot|bots|deleting negative|ai generated|chatgpt|generated by|generated by the same|automated|auto replies|auto responder|engagement bait|paid subscribers|copy pasted|crypto bots|suspiciously high engagement|replies sound corporate|zero soul|black mirror|dystopian)\b|(?:look|looks|feel|feels|sound|sounds)\s.{0,24}\bfake\b|\bfake\s(?:comments|views|reactions|positivity)\b/i;
const emojiOnlyPattern = /^[\p{Emoji_Presentation}\p{Extended_Pictographic}\s]+$/u;
const positiveEmojiPattern = /^[❤♥💕💖💗💓💞💝💘🫶👍👌👏🙌🙏🔥💯✨🎉😍🥰😊☺🤍🩷💐🌹🌷🌺🌸🌼😘💋〰\s]+$/u;
const positiveEmojiSignalPattern = /[❤♥💕💖💗💓💞💝💘🫶👍👌👏🙌🙏🔥💯✨🎉😍🥰😊☺🤍🩷💐🌹🌷🌺🌸🌼😘💋]/gu;
const positiveShortPattern = /\b(lovely|beautiful|great|nice|very nice|amazing|wonderful|perfect|cool|i like|really like|love it|love this|nice video|wowx*|woww+|muito bom|maravilhos[ao]s?|adorando|adorei|amei|gostei|bela+|que rico|kerrico|merci|j[’']adore|j[’']aime|mükemmel|замечательн[а-я]*|спасибо|класс|супер|нравится|обожаю|ух ты|потрясающ[а-я]*|завораживающ[а-я]*|красив[а-я]*|прекрасн[а-я]*|мил[а-я]*|крисс?)\b|μαγειρ[εέ]μα|τρελαν[εέ]ς/i;
const cyrillicPositivePattern = /(потрясающ[а-я]*|завораживающ[а-я]*|красив[а-я]*|прекрасн[а-я]*|замечательн[а-я]*|мил[а-я]*|спасибо|класс|супер|нравится|обожаю|ух ты|крисс?)/i;

export function analyzeComment(comment) {
  const normalized = comment.trim().toLowerCase();
  const language = detectLanguage(comment);

  if (linkPattern.test(comment)) return deletion("link", language);
  if (channelMentionPattern.test(comment)) return deletion("channel_promo", language);
  if (spamPattern.test(comment)) return deletion("spam", language);
  if (sexualPattern.test(comment) || explicitSexualPattern.test(comment) || cyrillicSexualPattern.test(comment) || turkishSexualPattern.test(comment) || sexualContextPattern.test(comment) || greekSexualPattern.test(comment)) return deletion("sexual", language);
  if (hatePattern.test(comment)) return deletion("hate", language);
  if (politicalPattern.test(comment)) return deletion("political", language);

  if (isPositiveReaction(comment)) {
    return safeResult(comment, fallbackLanguage(language), "positive_reaction");
  }

  if (softAppearancePattern.test(comment) && !sexualContextPattern.test(comment)) {
    return safeResult(comment, fallbackLanguage(language), "appearance_compliment");
  }

  if (meaningless.has(normalized) || normalized.length <= 2 || emojiOnlyPattern.test(normalized)) {
    return deletion("meaningless", language);
  }

  if (looksDuplicated(normalized)) return deletion("duplicate", language);
  if (!hasPositiveComparisonContext(comment) && !/\b(less fake|not fake)\b/i.test(comment) && reviewPattern.test(comment)) {
    return review("sensitive_or_negative", language);
  }
  if (positiveShortPattern.test(normalized) || cyrillicPositivePattern.test(normalized)) {
    return safeResult(comment, fallbackLanguage(language), "positive_reaction");
  }
  if (isShortPositiveUnknown(comment, normalized)) {
    return safeResult(comment, fallbackLanguage(language), "positive_reaction");
  }

  if (language.code === "unknown" || language.confidence < 0.45) {
    return review("unclear_language", language);
  }
  if (!isPositiveAsmrComment(normalized) && !positiveShortPattern.test(normalized) && normalized.split(/\s+/).length <= 2 && normalized.length < 18) {
    return review("unclear", language);
  }

  return safeResult(comment, language);
}

function safeResult(comment, language, category = "safe") {
  return {
    action: "reply",
    category,
    detectedLanguage: language.name,
    replyLanguage: language.name,
    languageConfidence: language.confidence,
    reply: generateWarmReply(comment, language.code),
  };
}

export function validateReply(reply, maxLength = 120) {
  if (!reply || reply === "DELETE") return { safe: false, reason: "empty_or_delete" };
  if (reply.length > maxLength) return { safe: false, reason: "too_long" };
  if (linkPattern.test(reply)) return { safe: false, reason: "contains_link" };
  if (spamPattern.test(reply)) return { safe: false, reason: "promotional" };
  if (sexualPattern.test(reply) || explicitSexualPattern.test(reply) || cyrillicSexualPattern.test(reply) || turkishSexualPattern.test(reply)) return { safe: false, reason: "nsfw" };
  return { safe: true };
}

function deletion(category, language) {
  return {
    action: "delete",
    category,
    detectedLanguage: language.name,
    replyLanguage: null,
    languageConfidence: language.confidence,
    reply: "DELETE",
  };
}

function review(category, language) {
  return {
    action: "review",
    category,
    detectedLanguage: language.name,
    replyLanguage: null,
    languageConfidence: language.confidence,
    reply: "REVIEW",
  };
}

function looksDuplicated(text) {
  const words = text.split(/\s+/).filter(Boolean);
  return words.length >= 4 && new Set(words).size <= Math.ceil(words.length / 2);
}

function isPositiveAsmrComment(text) {
  return /\b(nice|lovely|beautiful|great|relax|relaxing|calming|tingles|amazing|perfect|love|like this|really like|sleepy|so good|good sounds|soft sounds|w video|bro cooked|fell asleep|lowkey fire|fire tho|slapped tho|kinda relaxing|got me|i should sleep)\b/i.test(text);
}

function stripEmojiModifiers(text) {
  return text.replace(/\uFE0F/g, "");
}

function isPositiveReaction(comment) {
  const normalized = stripEmojiModifiers(comment.trim());
  if (positiveEmojiPattern.test(normalized)) return true;

  const positiveEmojiCount = (normalized.match(positiveEmojiSignalPattern) || []).length;
  return positiveEmojiCount >= 2 || (positiveEmojiCount >= 1 && positiveShortPattern.test(normalized));
}

function isShortPositiveUnknown(comment, normalized) {
  const textLength = [...comment.trim()].length;
  return textLength <= 28 && (
    positiveShortPattern.test(normalized)
    || cyrillicPositivePattern.test(normalized)
    || positiveEmojiSignalPattern.test(stripEmojiModifiers(comment))
  );
}

function hasPositiveComparisonContext(text) {
  return /\b(compared to|instead of|rather than|unlike|way better than|more natural than|less annoying than|those channels|modern content|most videos|most channels)\b/i.test(text)
    || /\b(don't|don’t|doesn't|doesn’t|isn't|isn’t|aren't|aren’t|not)\b.{0,100}\bfake reactions\b/i.test(text);
}

function detectLanguage(comment) {
  const text = comment.toLowerCase();
  const latinWords = comment.match(/[a-z]{2,}/gi) || [];
  if (/[а-яё]/i.test(comment)) return { code: "ru", name: "Russian", confidence: 0.97 };
  if (positiveEmojiPattern.test(stripEmojiModifiers(comment.trim()))) {
    return { code: "emoji", name: "Emoji", confidence: 0.85 };
  }
  if (/\b(love from|love this|love it)\b/i.test(text)) {
    return { code: "en", name: "English", confidence: 0.92 };
  }
  if (/[ãõ]/i.test(comment) || /\b(t[oô]\s+adorando|adorando|adorei|amei|gostei|obrigad[ao]|maravilhos[ao]s?|lind[ao]s?|bela+|graça|cozinha|bolonhesa|muito bom|relaxante)\b/i.test(text)) {
    return { code: "pt", name: "Portuguese", confidence: 0.9 };
  }
  if (/[α-ωάέήίόύώϊΐϋΰ]/i.test(comment)) {
    return { code: "el", name: "Greek", confidence: 0.9 };
  }
  if (/[àâçéèêëîïôûùüÿœ]|j[’'](?:adore|aime)/i.test(comment) || /\b(merci|bonjour|relaxant|sommeil|parfait)\b/i.test(text)) {
    return { code: "fr", name: "French", confidence: 0.9 };
  }
  if (/[çğıİöşü]/i.test(comment) || /\b(mükemmel|güzel|bayansın|harika|teşekkür)\b/i.test(text)) {
    return { code: "tr", name: "Turkish", confidence: 0.9 };
  }
  if (/[áíóúñ¿¡]/i.test(comment) || /\b(gracias|hola|perfecta|relajante|sonido|dormir|microfono|aqui)\b/i.test(text)) {
    return { code: "es", name: "Spanish", confidence: 0.93 };
  }
  if (/\b(kerrico|que rico)\b/i.test(text)) {
    return { code: "es", name: "Spanish", confidence: 0.75 };
  }
  if (/[äöüß]/i.test(comment) || /\b(danke|entspannend|schlaf|perfekt|gerausch)\b/i.test(text)) {
    return { code: "de", name: "German", confidence: 0.9 };
  }
  if (/\b(thank|thanks|sleep|relax|relaxing|calming|sound|sounds|mic|nice|beautiful|perfect|helped|watching|tingles|love this|amazing|w video|bro cooked|lowkey fire|slapped tho|wowx*|woww+)\b/i.test(text)) {
    return { code: "en", name: "English", confidence: 0.92 };
  }
  if (latinWords.length >= 2) {
    return { code: "en", name: "English", confidence: 0.62 };
  }
  return { code: "unknown", name: "Unknown", confidence: 0.2 };
}

function fallbackLanguage(language) {
  return language.code === "unknown" || language.code === "emoji"
    ? { code: "en", name: "English", confidence: language.confidence }
    : language;
}

function generateWarmReply(comment, languageCode) {
  const text = comment.toLowerCase();
  const replyBank = {
    en: {
      sleep: [
        "So glad it helped you relax. Sleep well tonight.",
        "Happy it helped you unwind. Rest well.",
        "That means a lot. Hope you sleep peacefully.",
      ],
      sound: [
        "Thank you, I'm glad the sounds felt good.",
        "So happy you liked the sounds.",
        "Glad the audio felt relaxing for you.",
      ],
      reaction: [
        "Thank you so much ❤️",
        "So sweet, thank you ❤️",
        "Really appreciate it ❤️",
      ],
      fallback: [
        "Thank you for watching, I'm really glad you enjoyed it.",
        "So glad you enjoyed it, thank you for being here.",
        "Thanks for watching, happy you liked it.",
        "I really appreciate you watching.",
        "Glad you enjoyed this one.",
      ],
    },
    es: {
      sleep: [
        "Me alegra mucho que te haya ayudado a relajarte.",
        "Que bueno que te ayudo a descansar.",
      ],
      sound: [
        "Gracias, me alegra que los sonidos se sientan bien.",
        "Me alegra que te hayan gustado los sonidos.",
      ],
      reaction: ["Muchas gracias ❤️", "Gracias de corazon ❤️", "Que lindo, gracias ❤️"],
      fallback: [
        "Gracias por mirar, me alegra mucho que te haya gustado.",
        "Muchas gracias por verlo, me alegra que te guste.",
        "Gracias, me alegra que hayas disfrutado el video.",
      ],
    },
    ru: {
      sleep: [
        "Рада, что видео помогло расслабиться. Спокойной ночи.",
        "Очень рада, что помогло отдохнуть.",
      ],
      sound: ["Спасибо, рада, что звук тебе понравился.", "Рада, что звуки зашли."],
      reaction: ["Спасибо большое ❤️", "Очень приятно, спасибо ❤️", "Спасибо, мне очень приятно ❤️"],
      fallback: [
        "Спасибо за просмотр, очень рада, что тебе понравилось.",
        "Спасибо, рада, что тебе понравилось.",
        "Очень приятно, спасибо за просмотр.",
      ],
    },
    fr: {
      sleep: ["Ravi que la video t'ait aide a te detendre.", "Heureux que ca t'ait aide a te relaxer."],
      sound: ["Merci, content que les sons soient agreables.", "Merci, ravi que les sons te plaisent."],
      reaction: ["Merci beaucoup ❤️", "C'est adorable, merci ❤️", "Merci, ca me touche ❤️"],
      fallback: [
        "Merci d'avoir regarde, je suis content que ca t'ait plu.",
        "Merci beaucoup, ravi que tu aies aime.",
        "Merci d'etre la, ca me fait plaisir.",
      ],
    },
    de: {
      sleep: ["Freut mich, dass es dir beim Entspannen geholfen hat.", "Schon, dass es dir beim Abschalten hilft."],
      sound: ["Danke, schon dass sich die Sounds gut anfuhlen.", "Freut mich, dass dir die Sounds gefallen."],
      reaction: ["Vielen Dank ❤️", "Das ist lieb, danke ❤️", "Danke dir sehr ❤️"],
      fallback: [
        "Danke fürs Zuschauen, freut mich sehr, dass es dir gefallt.",
        "Danke, freut mich dass du es magst.",
        "Vielen Dank fürs Zuschauen.",
      ],
    },
    pt: {
      sleep: ["Fico feliz que tenha ajudado voce a relaxar.", "Que bom que ajudou voce a descansar."],
      sound: ["Obrigada, fico feliz que os sons tenham ficado bons.", "Fico feliz que voce gostou dos sons."],
      reaction: ["Muito obrigada ❤️", "Que carinho, obrigada ❤️", "Obrigada de coracao ❤️"],
      fallback: [
        "Obrigada por assistir, fico feliz que tenha gostado.",
        "Muito obrigada por assistir.",
        "Fico feliz que voce tenha gostado.",
      ],
    },
    tr: {
      sleep: ["Rahatlamana yardimci olmasina cok sevindim.", "Dinlenmene iyi gelmesine sevindim."],
      sound: ["Tesekkur ederim, sesleri begenmene sevindim.", "Sesleri begenmene cok sevindim."],
      reaction: ["Cok tesekkur ederim ❤️", "Cok naziksin, tesekkurler ❤️", "Cok mutlu oldum, tesekkurler ❤️"],
      fallback: [
        "Izledigin icin tesekkur ederim, begenmene sevindim.",
        "Cok tesekkurler, begenmene sevindim.",
        "Izledigin icin cok tesekkur ederim.",
      ],
    },
    el: {
      sleep: ["Χαίρομαι που σε βοήθησε να χαλαρώσεις.", "Χαίρομαι που σε ξεκούρασε."],
      sound: ["Ευχαριστώ, χαίρομαι που σου άρεσαν οι ήχοι.", "Χαίρομαι που οι ήχοι ήταν ευχάριστοι."],
      reaction: ["Σε ευχαριστώ πολύ ❤️", "Πολύ γλυκό, ευχαριστώ ❤️", "Χαίρομαι πολύ, ευχαριστώ ❤️"],
      fallback: [
        "Ευχαριστώ που το είδες, χαίρομαι που σου άρεσε.",
        "Σε ευχαριστώ πολύ που είσαι εδώ.",
        "Χαίρομαι που σου άρεσε.",
      ],
    },
  };

  const replies = replyBank[languageCode] || replyBank.en;
  if (isPositiveReaction(comment)) {
    return pickReply(replies.reaction, comment);
  }
  if (text.includes("sleep") || text.includes("relax") || text.includes("calming") || text.includes("relaxante")) {
    return pickReply(replies.sleep, comment);
  }
  if (text.includes("sound") || text.includes("sounds") || text.includes("mic") || text.includes("sonido") || text.includes("microfono") || text.includes("som")) {
    return pickReply(replies.sound, comment);
  }
  return pickReply(replies.fallback, comment);
}

function pickReply(options, seedText) {
  const seed = [...seedText].reduce((sum, char) => sum + char.codePointAt(0), 0);
  return options[seed % options.length];
}
